# Generated by Django 5.2.4 on 2025-08-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('FlightID', models.IntegerField(primary_key=True, serialize=False)),
                ('AirlineName', models.CharField(max_length=100)),
                ('FlightNumber', models.CharField(max_length=20, unique=True)),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('DepartureTime', models.DateTimeField()),
                ('ArrivalTime', models.DateTimeField()),
                ('TotalSeats', models.IntegerField()),
                ('AvailableSeats', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.IntegerField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateTimeField(auto_now_add=True)),
                ('TravelDate', models.DateField()),
                ('TotalPassengers', models.IntegerField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BookingStatus', models.CharField(max_length=50)),
                ('FlightID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.flight')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('PassengerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('SeatNumber', models.CharField(max_length=10)),
                ('BookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.IntegerField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('PaymentStatus', models.CharField(max_length=50)),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='QR_Ticket',
            fields=[
                ('TicketID', models.IntegerField(primary_key=True, serialize=False)),
                ('QRCodeData', models.TextField()),
                ('IssuedDate', models.DateTimeField(auto_now_add=True)),
                ('BookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.booking')),
            ],
        ),
    ]
